"""ITSM classification: Talep → Birim → Modül → Süreç/Talep tipi."""

from __future__ import annotations

from dataclasses import dataclass

from text_norm import fold_tr


@dataclass(frozen=True)
class TaxonomyPath:
    talep_turu: str
    talep_turu_label: str
    birim: str
    birim_label: str
    modul: str
    modul_label: str
    surec: str
    surec_label: str
    keywords: tuple[str, ...]
    clarify_hint: str


PATHS: tuple[TaxonomyPath, ...] = (
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "ofis_ekipmani",
        "Ofis Ekipmanı",
        "toner_kartus_talebi",
        "Toner/Kartuş Talebi",
        (
            "toner",
            "kartuş",
            "kartus",
            "mürekkep",
            "murekkep",
            "bitti",
            "toner bitti",
            "kartuş talebi",
            "toner/kartuş",
        ),
        "Yazıcının marka ve modeli nedir, doğru toner kodunu belirleyebilmemiz için gerekli?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "satinalma_malzeme",
        "Satınalma/Malzeme",
        "kirtasiye_malzeme_talebi",
        "Kırtasiye Malzeme Talebi",
        (
            "kırtasiye",
            "kirtasiye",
            "kalem",
            "defter",
            "a4",
            "kağıt",
            "kagit",
            "dosya",
            "zımba",
            "post-it",
            "zimba",
            "malzeme",
        ),
        "Hangi malzemelerden ne miktarda ihtiyacınız var, liste hâlinde belirtebilir misiniz?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "sunucu_sistem",
        "Sunucu/Sistem",
        "sunucu_servis_kesintisi",
        "Sunucu/Servis Kesintisi",
        (
            "sunucu",
            "server",
            "servis kesintisi",
            "sistem çöktü",
            "sistem coktu",
            "tüm sistem",
            "erişilemez",
            "crm sistemi",
            "erp sistemi",
            "muhasebe sistemi",
            "sunucu/servis",
            "kesintisi",
        ),
        "Sistem tamamen erişilemez durumda mı, yoksa bazı işlemler yapılabiliyor ama yavaş mı çalışıyor?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "bina_tesis_bakim",
        "Bina/Tesis Bakım",
        "klima_isitma_arizasi",
        "Klima/Isıtma Arızası",
        (
            "klima",
            "ısıtma",
            "isitma",
            "soğutmuyor",
            "sogutmuyor",
            "gürültü",
            "su damlıyor",
            "kalorifer",
            "dondurucu",
            "sıcak",
            "sicak",
            "soğuk",
            "soguk",
            "klima/isıtma",
        ),
        "Klima hiç çalışmıyor mu yoksa çalışıyor ama yeterince soğutmuyor/ısıtmıyor mu?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "guvenlik__ulasim",
        "Güvenlik & Ulaşım",
        "kayip_giris_karti",
        "Kayıp Giriş Kartı",
        (
            "kart",
            "giriş kartı",
            "giris karti",
            "kaybettim",
            "kayıp kart",
            "kartım çalındı",
            "turnike",
            "kayıp",
            "giriş",
            "kartı",
        ),
        "Kartınızı ne zaman ve nerede kaybettiğinizi hatırlıyor musunuz? Güvenlik kaydı için gerekli olacak.",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "ofis_ekipmani",
        "Ofis Ekipmanı",
        "yazici_fotokopi_ariza_bildirimi",
        "Yazıcı/Fotokopi Arıza Bildirimi",
        (
            "yazıcı",
            "yazici",
            "printer",
            "fotokopi",
            "kağıt sıkıştı",
            "kagit sikisti",
            "çizgili basıyor",
            "cizgili basiyor",
            "basmıyor",
            "basmiyor",
            "çıktı alamıyorum",
            "yazıcı/fotokopi",
            "arıza",
        ),
        "Yazıcıda bir hata kodu veya ışık uyarısı görünüyor mu, görünüyorsa nedir?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "guvenlik_ve_erisim",
        "Güvenlik ve Erişim",
        "yeni_kullanici_hesabi",
        "Yeni Kullanıcı Hesabı",
        (
            "yeni kullanıcı",
            "hesap açma",
            "ad hesabı",
            "işe başlıyor",
            "ise basliyor",
            "mail adresi açılsın",
            "yeni personel",
            "kullanıcı hesabı",
            "hesap oluşturma",
            "yeni",
            "kullanıcı",
            "hesabı",
        ),
        "Kullanıcı için standart erişim paketi mi yeterli, yoksa ek özel sistem/uygulama erişimleri de gerekiyor mu?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "i̇nsan_kaynaklari",
        "İnsan Kaynakları",
        "i̇zin_yonetimi",
        "İzin Yönetimi",
        "i̇zin_i̇ptal_degisiklik",
        "İzin İptal/Değişiklik",
        (
            "izin iptal",
            "iznimi iptal",
            "izin değişikliği",
            "tarih uymuyor",
            "yanlış izin",
            "izin talebimi",
            "i̇zin",
            "i̇ptal/değişiklik",
        ),
        "İptal etmek veya değiştirmek istediğiniz izninizin tarih aralığı nedir?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "sunucu_sistem",
        "Sunucu/Sistem",
        "veritabani_erisim_hatasi",
        "Veritabanı Erişim Hatası",
        (
            "veritabanı",
            "veritabani",
            "database",
            "bağlanamıyorum",
            "connection timeout",
            "token expired",
            "rapor çekmeye",
            "sql hatası",
            "erişim",
            "hatası",
        ),
        "Bu hatayı sadece siz mi alıyorsunuz, yoksa aynı raporu kullanan diğer ekip arkadaşlarınız da mı yaşıyor?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "donanim",
        "Donanım",
        "monitor_cevre_birimi_arizasi",
        "Monitör/Çevre Birimi Arızası",
        (
            "monitör",
            "monitor",
            "ekran",
            "ikinci ekran",
            "klavye",
            "mouse",
            "fare",
            "kulaklık",
            "tarayıcı",
            "çevre birimi",
            "görüntü gelmiyor",
            "çizgili ekran",
            "monitör/çevre",
            "birimi",
        ),
        "Cihaz hiç açılmıyor mu (ışık yanmıyor) yoksa açılıyor ama görüntü/sinyal mi gelmiyor?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "donanim",
        "Donanım",
        "bilgisayar_ariza_onarim",
        "Bilgisayar Arıza/Onarım",
        (
            "bilgisayar",
            "laptop",
            "dizüstü",
            "dizustu",
            "pc",
            "açılmıyor",
            "acilmiyor",
            "bozuldu",
            "mavi ekran",
            "donuyor",
            "fan sesi",
            "kapanıyor",
            "su döküldü",
            "arıza/onarım",
        ),
        "Bilgisayarınız hiç açılmıyor mu, yoksa açılıp belirli bir noktada mı donuyor/kapanıyor?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "ag_network",
        "Ağ/Network",
        "vpn_erisim_sorunu",
        "VPN Erişim Sorunu",
        (
            "vpn",
            "vpn bağlanmıyor",
            "vpn kopuyor",
            "sertifika hatası",
            "uzaktan erişim",
            "evden çalışma",
            "şirket ağı",
            "erişim",
        ),
        "VPN'e bağlanırken aldığınız hata mesajını veya hata kodunu paylaşabilir misiniz?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "guvenlik_ve_erisim",
        "Güvenlik ve Erişim",
        "sifre_sifirlama",
        "Şifre Sıfırlama",
        (
            "şifre",
            "sifre",
            "parola",
            "unuttum",
            "hesabım kilitlendi",
            "giriş yapamıyorum",
            "giriş bilgileri",
            "şifre sıfırlama",
            "şifremi unuttum",
            "sıfırlama",
        ),
        "Şifresini sıfırlamak istediğiniz sistem hangisi (Windows/AD, e-posta, SAP vb.)?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "finans",
        "Finans",
        "masraf__odeme",
        "Masraf & Ödeme",
        "avans_talebi",
        "Avans Talebi",
        (
            "avans",
            "avans talebi",
            "nakit avans",
            "iş seyahati avans",
            "harcırah",
        ),
        "Talep ettiğiniz avans tutarı ve seyahat/görev tarihleri nedir?",
    ),
    TaxonomyPath(
        "bilgi",
        "Bilgi Talebi (Information)",
        "finans",
        "Finans",
        "masraf__odeme",
        "Masraf & Ödeme",
        "masraf_harcama_formu_onayi",
        "Masraf/Harcama Formu Onayı",
        (
            "masraf",
            "harcama",
            "masraf formu",
            "harcama formu",
            "masraf onayı",
            "masrafım beklemede",
            "masraf/harcama",
            "formu",
            "onayı",
        ),
        "Masraf formunuzun onay/form numarasını veya oluşturduğunuz tarihi paylaşabilir misiniz?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "guvenlik_ve_erisim",
        "Güvenlik ve Erişim",
        "sistem_klasor_yetki_talebi",
        "Sistem/Klasör Yetki Talebi",
        (
            "yetki",
            "erişim yetkisi",
            "klasör yetkisi",
            "paylaşımlı sürücü",
            "ortak klasör",
            "drive izni",
            "sap modül yetkisi",
            "düzenleme yetkisi",
            "sistem/klasör",
        ),
        "Talep ettiğiniz klasöre/sisteme okuma mı yoksa yazma/düzenleme yetkisi mi gerekiyor?",
    ),
    TaxonomyPath(
        "bilgi",
        "Bilgi Talebi (Information)",
        "finans",
        "Finans",
        "masraf__odeme",
        "Masraf & Ödeme",
        "fatura_odeme_takibi",
        "Fatura Ödeme Takibi",
        (
            "fatura",
            "ödeme",
            "odendi mi",
            "ödenmedi",
            "fatura ödemesi",
            "tedarikçi fatura",
            "fatura no",
            "takibi",
        ),
        "Sorguladığınız faturanın numarasını veya tedarikçi firma adını paylaşabilir misiniz?",
    ),
    TaxonomyPath(
        "bilgi",
        "Bilgi Talebi (Information)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "guvenlik__ulasim",
        "Güvenlik & Ulaşım",
        "servis_guzergah_talebi",
        "Servis Güzergah Talebi",
        (
            "servis",
            "güzergah",
            "guzergah",
            "servis saati",
            "servis kalkış",
            "durak ekleme",
            "servis değişti mi",
        ),
        "Mevcut servis saatlerini mi öğrenmek istiyorsunuz, yoksa güzergahta bir durak değişikliği mi talep ediyorsunuz?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "donanim",
        "Donanım",
        "yeni_ekipman_kurulumu",
        "Yeni Ekipman Kurulumu",
        (
            "yeni bilgisayar",
            "ekipman kurulumu",
            "yeni laptop",
            "stajyer için bilgisayar",
            "monitör kurulumu",
            "cihaz hazırlanması",
            "donanım talebi",
            "yeni",
            "ekipman",
            "kurulumu",
        ),
        "Talep edilen ekipman sadece dizüstü bilgisayar mı, yoksa monitör ve çevre birimleri de dahil mi?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "i̇nsan_kaynaklari",
        "İnsan Kaynakları",
        "bordro__ozluk",
        "Bordro & Özlük",
        "ozluk_calisma_belgesi_talebi",
        "Özlük/Çalışma Belgesi Talebi",
        (
            "çalışma belgesi",
            "calisma belgesi",
            "hizmet dökümü",
            "özlük belgesi",
            "vize yazısı",
            "banka yazısı",
            "sgk yazısı",
            "özlük/çalışma",
            "belgesi",
            "evlendim",
            "evlilik",
            "evlilik bildirimi",
            "soyadı değişikliği",
            "soyadi degisikligi",
            "soyadı",
            "soyisim",
            "özel sağlık sigortası",
            "sağlık sigortası",
            "saglik sigortasi",
            "sigorta poliçesi",
            "aile kapsamı",
            "eşimi",
            "esimi",
            "sağlık poliçesi",
            "özlük bilgisi",
            "evrak yükleme",
            "ik portalı",
        ),
        "Belgeyi e-posta ile (e-imzalı) mi almak istersiniz, yoksa ıslak imzalı elden teslim mi tercih edersiniz?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "ag_network",
        "Ağ/Network",
        "wi-fi_baglanti_sorunu",
        "Wi-Fi Bağlantı Sorunu",
        (
            "wifi",
            "wi-fi",
            "kablosuz ağ",
            "wifi yavaş",
            "wifi bağlanmıyor",
            "misafir wifi",
            "sinyal zayıf",
            "bağlantı",
        ),
        "Bu sorun sadece belirli bir odada/katta mı yaşanıyor, yoksa ofis genelinde mi?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "yazilim",
        "Yazılım",
        "yazilim_lisans_kurulum_talebi",
        "Yazılım Lisans/Kurulum Talebi",
        (
            "lisans",
            "yazılım kurulumu",
            "program kurulumu",
            "office kurulumu",
            "photoshop",
            "autocad",
            "visio",
            "illustrator",
            "tableau",
            "lisansım bitti",
            "yazılım",
            "lisans/kurulum",
        ),
        "Hangi yazılımın hangi sürümüne ihtiyacınız var ve ne amaçla kullanacaksınız?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "bina_tesis_bakim",
        "Bina/Tesis Bakım",
        "elektrik_aydinlatma_arizasi",
        "Elektrik/Aydınlatma Arızası",
        (
            "elektrik",
            "lamba",
            "aydınlatma",
            "aydinlatma",
            "ışıklar yanmıyor",
            "priz çalışmıyor",
            "elektrik kesildi",
            "karanlık",
            "kıvılcım",
            "elektrik/aydınlatma",
        ),
        "Sorun tüm ofiste/katta mı yoksa sadece belirli bir masada/odada mı yaşanıyor?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "yazilim",
        "Yazılım",
        "uygulama_hatasi_outlook_teams_excel_vb",
        "Uygulama Hatası (Outlook/Teams/Excel vb.)",
        (
            "outlook",
            "teams",
            "excel",
            "word",
            "uygulama çöktü",
            "program açılmıyor",
            "hata veriyor",
            "senkronize olmuyor",
            "ekran paylaşımı",
            "bozuk dosya",
            "uygulama",
            "hatası",
            "outlook/teams/excel",
        ),
        "Hangi uygulamada (Outlook/Teams/Excel/SAP) hangi işlemi yaparken hata alıyorsunuz?",
    ),
    TaxonomyPath(
        "hizmet",
        "Hizmet Talebi (Service Request)",
        "i̇dari_i̇sler",
        "İdari İşler",
        "satinalma_malzeme",
        "Satınalma/Malzeme",
        "ofis_mobilya_degisimi",
        "Ofis Mobilya Değişimi",
        (
            "sandalye",
            "koltuk",
            "masa",
            "mobilya",
            "çekmece",
            "sandalyem kırıldı",
            "ergonomik sandalye",
            "mobilya değişimi",
            "ofis",
            "değişimi",
        ),
        "Hasarlı mobilyanın türü nedir ve hasarın boyutunu gösteren bir fotoğraf paylaşabilir misiniz?",
    ),
    TaxonomyPath(
        "arıza",
        "Arıza (Incident)",
        "bilgi_teknolojileri",
        "Bilgi Teknolojileri",
        "ag_network",
        "Ağ/Network",
        "i̇nternet_baglanti_sorunu",
        "İnternet Bağlantı Sorunu",
        (
            "internet",
            "internet kesildi",
            "internet yok",
            "bağlantı kopuyor",
            "ağ kesintisi",
            "internet yavaş",
            "i̇nternet",
            "bağlantı",
        ),
        "Bu internet kesintisi sadece sizin cihazınızda mı yoksa kattaki diğer kişilerde de var mı?",
    ),
    TaxonomyPath(
        "bilgi",
        "Bilgi Talebi (Information)",
        "i̇nsan_kaynaklari",
        "İnsan Kaynakları",
        "i̇zin_yonetimi",
        "İzin Yönetimi",
        "yillik_i̇zin_talebi_bakiye_sorgulama",
        "Yıllık İzin Talebi/Bakiye Sorgulama",
        (
            "izin bakiyesi",
            "yıllık izin",
            "kalan izin",
            "kaç gün iznim kaldı",
            "izin hakkım",
            "izin sorgulama",
            "yıllık",
            "i̇zin",
            "talebi/bakiye",
            "sorgulama",
        ),
        "Sadece kalan izin bakiyenizi mi öğrenmek istiyorsunuz, yoksa yeni bir izin talebi mi oluşturmak istiyorsunuz?",
    ),
)


# Core distinctive keywords
STRONG_KEYWORDS = {
    "laptop", "bilgisayar", "dizüstü", "dizustu", "masaüstü", "masaustu", "cihaz",
    "vpn", "wifi", "wi-fi", "internet", "şifre", "sifre", "parola", "unuttum",
    "outlook", "teams", "excel", "word", "yazıcı", "yazici", "printer", "toner", "kartuş", "kartus",
    "yetki", "izin", "bordro", "maaş", "maas", "masraf", "avans", "fatura", "klima",
    "sunucu", "server", "kartım", "kart", "fotokopi", "kırtasiye", "kirtasiye", "servis",
    "monitör", "monitor", "lisans", "elektrik",
    "evlendim", "evlilik", "soyadı", "soyadi", "sigorta", "sigortası", "özlük", "ozluk", "poliçe", "eşimi"
}


def _hits(text: str, keywords: tuple[str, ...]) -> list[str]:
    lowered = fold_tr(text)
    return [kw for kw in keywords if fold_tr(kw) in lowered or kw in lowered]


PROCESS_ALIASES = {
    # HR - Özlük
    "evlilik bildirimi": "ozluk_calisma_belgesi_talebi",
    "soyadı değişikliği": "ozluk_calisma_belgesi_talebi",
    "soyadi degisikligi": "ozluk_calisma_belgesi_talebi",
    "öss (özel sağlık sigortası) aile kapsamı ekleme": "ozluk_calisma_belgesi_talebi",
    "oss (ozel saglik sigortasi) aile kapsami ekleme": "ozluk_calisma_belgesi_talebi",
    "sgk giriş/çıkış evrakı talebi": "ozluk_calisma_belgesi_talebi",
    "sgk giris/cikis evraki talebi": "ozluk_calisma_belgesi_talebi",
    "bordro/maaş bilgisi talebi": "ozluk_calisma_belgesi_talebi",
    "bordro/maas bilgisi talebi": "ozluk_calisma_belgesi_talebi",
    "bordro vergi matrahı itirazı": "ozluk_calisma_belgesi_talebi",
    "bordro vergi matrahi itirazi": "ozluk_calisma_belgesi_talebi",
    "bes (bireysel emeklilik) kesintisi talebi": "ozluk_calisma_belgesi_talebi",
    # HR - İzin
    "doğum/analık izni talebi": "i̇zin_i̇ptal_degisiklik",
    "dogum/analik izni talebi": "i̇zin_i̇ptal_degisiklik",
    "babalık izni talebi": "i̇zin_i̇ptal_degisiklik",
    "babalik izni talebi": "i̇zin_i̇ptal_degisiklik",
    "süt izni talebi": "i̇zin_i̇ptal_degisiklik",
    "sut izni talebi": "i̇zin_i̇ptal_degisiklik",
    "ücretsiz izin talebi": "i̇zin_i̇ptal_degisiklik",
    "ucretsiz izin talebi": "i̇zin_i̇ptal_degisiklik",
    "evlilik izni talebi": "i̇zin_i̇ptal_degisiklik",
    "vefat/mazeret izni talebi": "i̇zin_i̇ptal_degisiklik",
    "sağlık raporu/istirahat bildirimi": "i̇zin_i̇ptal_degisiklik",
    "saglik raporu/istirahat bildirimi": "i̇zin_i̇ptal_degisiklik",
    # Finans - Masraf
    "döviz kuru farkı/uyumsuzluğu": "masraf_harcama_formu_onayi",
    "doviz kuru farki/uyumsuzlugu": "masraf_harcama_formu_onayi",
    "harcama fişi kayıp beyanı": "masraf_harcama_formu_onayi",
    "harcama fisi kayip beyani": "masraf_harcama_formu_onayi",
    "kurumsal kredi kartı limit artırımı": "masraf_harcama_formu_onayi",
    "kurumsal kredi karti limit artirimi": "masraf_harcama_formu_onayi",
    "onay akışında yönetici görünmüyor sorunu": "masraf_harcama_formu_onayi",
    "onay akisinda yonetici gorunmuyor sorunu": "masraf_harcama_formu_onayi",
    # Finans - Fatura
    "tedarikçi ıban/vade mutabakatı": "fatura_odeme_takibi",
    "tedarikci iban/vade mutabakati": "fatura_odeme_takibi",
    "çoklu para birimli fatura girişi": "fatura_odeme_takibi",
    "coklu para birimli fatura girisi": "fatura_odeme_takibi",
    # İdari İşler
    "kargo/kurye teslimat takibi": "kirtasiye_malzeme_talebi",
    "toplantı odası ekipman arızası (clickshare/projeksiyon)": "yazici_fotokopi_ariza_bildirimi",
    "toplanti odasi ekipman arizasi (clickshare/projeksiyon)": "yazici_fotokopi_ariza_bildirimi",
    "ofis mobilya arızası (ergonomik masa/koltuk)": "ofis_mobilya_degisimi",
    "ofis mobilya arizasi (ergonomik masa/koltuk)": "ofis_mobilya_degisimi",
    "ziyaretçi giriş talebi": "kayip_giris_karti",
    "ziyaretci giris talebi": "kayip_giris_karti",
    "misafir otopark izni": "servis_guzergah_talebi",
    "bina içi teknik bakım talebi": "elektrik_aydinlatma_arizasi",
    "bina ici teknik bakim talebi": "elektrik_aydinlatma_arizasi",
}


def path_by_surec(surec: str) -> TaxonomyPath | None:
    surec_norm = fold_tr(surec)
    if surec_norm in PROCESS_ALIASES:
        surec_norm = fold_tr(PROCESS_ALIASES[surec_norm])

    for path in PATHS:
        if (
            path.surec == surec
            or fold_tr(path.surec) == surec_norm
            or fold_tr(path.surec_label) == surec_norm
            or path.surec == PROCESS_ALIASES.get(surec_norm)
        ):
            return path
    return None


def _from_path(
    path: TaxonomyPath,
    score: float,
    hits: list[str],
    source: str,
    *,
    model_confidence: float = 0.0,
) -> dict:
    return {
        "unclear": False,
        "score": score,
        "hits": hits,
        "source": source,
        "model_confidence": model_confidence,
        "talep_turu": path.talep_turu,
        "talep_turu_label": path.talep_turu_label,
        "birim": path.birim,
        "birim_label": path.birim_label,
        "modul": path.modul,
        "modul_label": path.modul_label,
        "surec": path.surec,
        "surec_label": path.surec_label,
        "path_label": (
            f"{path.talep_turu_label} → {path.birim_label} → "
            f"{path.modul_label} → {path.surec_label}"
        ),
        "clarify_hint": path.clarify_hint,
    }


def classify_request(text: str, min_score: int = 2) -> dict:
    """Keyword path first; TF-IDF NLU model fallback."""
    best: TaxonomyPath | None = None
    best_score = 0
    best_hits: list[str] = []
    for path in PATHS:
        hits = _hits(text, path.keywords)
        score = len(hits)
        if any(fold_tr(h) in STRONG_KEYWORDS or h in STRONG_KEYWORDS for h in hits):
            score += 2
        if score > best_score:
            best_score = score
            best = path
            best_hits = hits
            
    if best is not None and best_score >= min_score:
        return _from_path(best, best_score, best_hits, "keyword")

    try:
        from itsm_nlu import predict_surec
        pred = predict_surec(text)
        modeled = path_by_surec(str(pred.get("surec") or ""))
        conf = float(pred.get("confidence") or 0.0)
        if modeled is not None and conf >= 0.40:
            return _from_path(
                modeled,
                max(best_score, 2),
                best_hits,
                "model",
                model_confidence=conf,
            )
    except Exception:
        pass

    return {
        "unclear": True,
        "score": best_score,
        "hits": best_hits,
        "source": "none",
        "model_confidence": 0.0,
        "talep_turu": "",
        "talep_turu_label": "",
        "birim": "",
        "birim_label": "",
        "modul": "",
        "modul_label": "",
        "surec": "",
        "surec_label": "",
        "path_label": "",
        "clarify_hint": (
            best.clarify_hint
            if best
            else "Talebiniz Bilgi Teknolojileri, İdari İşler, İnsan Kaynakları veya Finans ile mi ilgili? Detay belirtebilir misiniz?"
        ),
    }


def path_line(classification: dict | None) -> str:
    if not classification or classification.get("unclear"):
        return "sınıf henüz net değil"
    return str(classification.get("path_label") or "")
